name: RUN SCRIPT LISTA
on:
  schedule:
    - cron: '0 */2 * * *'  # Esegui ogni 2 ore
  workflow_dispatch:  # Consente l'esecuzione manuale

jobs:
  extract-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml playwright bs4 rapidfuzz fuzzywuzzy python-Levenshtein
          playwright install 
      
      - name: Run extraction script
        run: python lista.py
      
      - name: Configura Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Stash delle modifiche locali (se presenti)
        run: |
          git diff --quiet || git stash

      - name: Scarica le ultime modifiche dal repository remoto
        run: git pull --rebase origin main

      - name: Ripristina le modifiche stashed (se presenti)
        run: |
          git stash list | grep -q "stash@{0}" && git stash pop || echo "Nessuna modifica da ripristinare"

      - name: Aggiungi il file generato al commit
        run: |
          git add .
          git commit -m "UPDATE" || echo "Nessuna modifica da commitare"

      - name: Pusha il cambiamento
        run: git push
